name: weatherio
description: Usecase project for Appinio.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  get: ^4.6.1
  intl: any
  url_launcher: ^6.0.17

dev_dependencies:
  auto_route_generator: any
  build_runner: any
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3
  mockito: ^5.0.16
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: PTSerif
      fonts:
        - asset: fonts/PTSerif-Bold.ttf
          weight: 700
    - family: GithubIcon
      fonts:
        - asset: fonts/GithubIcon.ttf